eight_points_guzzle:
  clients:
    atom:
      options:
        debug: false
        timeout: 10
        http_errors: true
        headers:
          Accept-Charset: "utf-8"
          Cache-Control: "no-cache"